version: "3"

tasks:
  grpc:ui:
    desc: Start gRPC UI for maestro service
    cmd: grpcui -plaintext localhost:7777

  run:
    desc: Run the maestro service
    cmd: go run .

  proto:gen:
    desc: Generate Go code from proto files
    cmd: protoc --go_out=. --go_opt=module=github.com/taldoflemis/box-box/maestro --go-grpc_out=. --go-grpc_opt=module=github.com/taldoflemis/box-box/maestro ../proto/maestro/**/*.proto -I ../proto

