services:
  nats:
    image: nats:latest
    command: -js
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - otel-network

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.10.0
    ports:
      - 16686:16686
      - 9411:9411
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge
