version: "3"

includes:
  paddock-gateway:
    taskfile: ./paddock-gateway/Taskfile.yaml
    dir: ./paddock-gateway

  maestro:
    taskfile: ./maestro/Taskfile.yaml
    dir: ./maestro

  panettiere:
    taskfile: ./panettiere/Taskfile.yaml
    dir: ./panettiere

  tifosi-load:
    taskfile: ./tifosi-load/Taskfile.yaml
    dir: ./tifosi-load
tasks:
  aux:up:
    desc: Start auxiliary services
    cmd: docker compose --profile aux up -d

  aux:down:
    desc: Stop auxiliary services
    cmd: docker compose --profile aux down

  telemetry:up:
    desc: Start telemetry services
    cmd: docker compose --profile telemetry up -d

  telemetry:down:
    desc: Stop telemetry services
    cmd: docker compose --profile telemetry down

  services:up:
    desc: Start services
    cmd: docker compose --profile services up --build -d

  services:down:
    desc: Stop services
    cmd: docker compose --profile services down

  nats:up:
    desc: Start NATS server
    cmd: docker compose up nats -d

  nats:down:
    desc: Stop NATS server
    cmd: docker compose down nats

  jaeger:up:
    desc: Start Jaeger
    cmd: docker compose up jaeger -d

  jaeger:down:
    desc: Stop Jaeger
    cmd: docker compose down jaeger

  otel-collector:up:
    desc: Start OTel Collector
    cmd: docker compose up otel-collector -d

  otel-collector:down:
    desc: Stop OTel Collector
    cmd: docker compose down otel-collector

  load-generator:up:
    desc: Start load generator
    cmd: docker compose --profile load up --build
