// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: panettiere/v1/service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorderKind int32

const (
	BorderKind_NoBorder    BorderKind = 0
	BorderKind_CreamCheese BorderKind = 1
	BorderKind_Cheddar     BorderKind = 2
	BorderKind_Chocolate   BorderKind = 3
)

// Enum value maps for BorderKind.
var (
	BorderKind_name = map[int32]string{
		0: "NoBorder",
		1: "CreamCheese",
		2: "Cheddar",
		3: "Chocolate",
	}
	BorderKind_value = map[string]int32{
		"NoBorder":    0,
		"CreamCheese": 1,
		"Cheddar":     2,
		"Chocolate":   3,
	}
)

func (x BorderKind) Enum() *BorderKind {
	p := new(BorderKind)
	*p = x
	return p
}

func (x BorderKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BorderKind) Descriptor() protoreflect.EnumDescriptor {
	return file_panettiere_v1_service_proto_enumTypes[0].Descriptor()
}

func (BorderKind) Type() protoreflect.EnumType {
	return &file_panettiere_v1_service_proto_enumTypes[0]
}

func (x BorderKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BorderKind.Descriptor instead.
func (BorderKind) EnumDescriptor() ([]byte, []int) {
	return file_panettiere_v1_service_proto_rawDescGZIP(), []int{0}
}

type PizzaSize int32

const (
	PizzaSize_Small  PizzaSize = 0
	PizzaSize_Medium PizzaSize = 1
	PizzaSize_Large  PizzaSize = 2
)

// Enum value maps for PizzaSize.
var (
	PizzaSize_name = map[int32]string{
		0: "Small",
		1: "Medium",
		2: "Large",
	}
	PizzaSize_value = map[string]int32{
		"Small":  0,
		"Medium": 1,
		"Large":  2,
	}
)

func (x PizzaSize) Enum() *PizzaSize {
	p := new(PizzaSize)
	*p = x
	return p
}

func (x PizzaSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PizzaSize) Descriptor() protoreflect.EnumDescriptor {
	return file_panettiere_v1_service_proto_enumTypes[1].Descriptor()
}

func (PizzaSize) Type() protoreflect.EnumType {
	return &file_panettiere_v1_service_proto_enumTypes[1]
}

func (x PizzaSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PizzaSize.Descriptor instead.
func (PizzaSize) EnumDescriptor() ([]byte, []int) {
	return file_panettiere_v1_service_proto_rawDescGZIP(), []int{1}
}

type DoughRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	Border        BorderKind             `protobuf:"varint,2,opt,name=border,proto3,enum=panettiere.v1.BorderKind" json:"border,omitempty"`
	Size          PizzaSize              `protobuf:"varint,3,opt,name=size,proto3,enum=panettiere.v1.PizzaSize" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoughRequest) Reset() {
	*x = DoughRequest{}
	mi := &file_panettiere_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoughRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoughRequest) ProtoMessage() {}

func (x *DoughRequest) ProtoReflect() protoreflect.Message {
	mi := &file_panettiere_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoughRequest.ProtoReflect.Descriptor instead.
func (*DoughRequest) Descriptor() ([]byte, []int) {
	return file_panettiere_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *DoughRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DoughRequest) GetBorder() BorderKind {
	if x != nil {
		return x.Border
	}
	return BorderKind_NoBorder
}

func (x *DoughRequest) GetSize() PizzaSize {
	if x != nil {
		return x.Size
	}
	return PizzaSize_Small
}

type DoughResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoughResponse) Reset() {
	*x = DoughResponse{}
	mi := &file_panettiere_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoughResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoughResponse) ProtoMessage() {}

func (x *DoughResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panettiere_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoughResponse.ProtoReflect.Descriptor instead.
func (*DoughResponse) Descriptor() ([]byte, []int) {
	return file_panettiere_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *DoughResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_panettiere_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_panettiere_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_panettiere_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_panettiere_v1_service_proto protoreflect.FileDescriptor

const file_panettiere_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1bpanettiere/v1/service.proto\x12\rpanettiere.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n" +
	"\fDoughRequest\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\tR\aOrderId\x121\n" +
	"\x06border\x18\x02 \x01(\x0e2\x19.panettiere.v1.BorderKindR\x06border\x12,\n" +
	"\x04size\x18\x03 \x01(\x0e2\x18.panettiere.v1.PizzaSizeR\x04size\")\n" +
	"\rDoughResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*G\n" +
	"\n" +
	"BorderKind\x12\f\n" +
	"\bNoBorder\x10\x00\x12\x0f\n" +
	"\vCreamCheese\x10\x01\x12\v\n" +
	"\aCheddar\x10\x02\x12\r\n" +
	"\tChocolate\x10\x03*-\n" +
	"\tPizzaSize\x12\t\n" +
	"\x05Small\x10\x00\x12\n" +
	"\n" +
	"\x06Medium\x10\x01\x12\t\n" +
	"\x05Large\x10\x022\xa0\x01\n" +
	"\x11PanettiereService\x12H\n" +
	"\tMakeDough\x12\x1b.panettiere.v1.DoughRequest\x1a\x1c.panettiere.v1.DoughResponse\"\x00\x12A\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x1d.panettiere.v1.StatusResponse\"\x00B.Z,github.com/taldoflemis/box-box/panettiere/v1b\x06proto3"

var (
	file_panettiere_v1_service_proto_rawDescOnce sync.Once
	file_panettiere_v1_service_proto_rawDescData []byte
)

func file_panettiere_v1_service_proto_rawDescGZIP() []byte {
	file_panettiere_v1_service_proto_rawDescOnce.Do(func() {
		file_panettiere_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_panettiere_v1_service_proto_rawDesc), len(file_panettiere_v1_service_proto_rawDesc)))
	})
	return file_panettiere_v1_service_proto_rawDescData
}

var file_panettiere_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_panettiere_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_panettiere_v1_service_proto_goTypes = []any{
	(BorderKind)(0),        // 0: panettiere.v1.BorderKind
	(PizzaSize)(0),         // 1: panettiere.v1.PizzaSize
	(*DoughRequest)(nil),   // 2: panettiere.v1.DoughRequest
	(*DoughResponse)(nil),  // 3: panettiere.v1.DoughResponse
	(*StatusResponse)(nil), // 4: panettiere.v1.StatusResponse
	(*emptypb.Empty)(nil),  // 5: google.protobuf.Empty
}
var file_panettiere_v1_service_proto_depIdxs = []int32{
	0, // 0: panettiere.v1.DoughRequest.border:type_name -> panettiere.v1.BorderKind
	1, // 1: panettiere.v1.DoughRequest.size:type_name -> panettiere.v1.PizzaSize
	2, // 2: panettiere.v1.PanettiereService.MakeDough:input_type -> panettiere.v1.DoughRequest
	5, // 3: panettiere.v1.PanettiereService.Status:input_type -> google.protobuf.Empty
	3, // 4: panettiere.v1.PanettiereService.MakeDough:output_type -> panettiere.v1.DoughResponse
	4, // 5: panettiere.v1.PanettiereService.Status:output_type -> panettiere.v1.StatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_panettiere_v1_service_proto_init() }
func file_panettiere_v1_service_proto_init() {
	if File_panettiere_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_panettiere_v1_service_proto_rawDesc), len(file_panettiere_v1_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_panettiere_v1_service_proto_goTypes,
		DependencyIndexes: file_panettiere_v1_service_proto_depIdxs,
		EnumInfos:         file_panettiere_v1_service_proto_enumTypes,
		MessageInfos:      file_panettiere_v1_service_proto_msgTypes,
	}.Build()
	File_panettiere_v1_service_proto = out.File
	file_panettiere_v1_service_proto_goTypes = nil
	file_panettiere_v1_service_proto_depIdxs = nil
}
