// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: panettiere/v1/service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PanettiereService_MakeDough_FullMethodName = "/panettiere.v1.PanettiereService/MakeDough"
	PanettiereService_Status_FullMethodName    = "/panettiere.v1.PanettiereService/Status"
)

// PanettiereServiceClient is the client API for PanettiereService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PanettiereServiceClient interface {
	MakeDough(ctx context.Context, in *DoughRequest, opts ...grpc.CallOption) (*DoughResponse, error)
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type panettiereServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPanettiereServiceClient(cc grpc.ClientConnInterface) PanettiereServiceClient {
	return &panettiereServiceClient{cc}
}

func (c *panettiereServiceClient) MakeDough(ctx context.Context, in *DoughRequest, opts ...grpc.CallOption) (*DoughResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoughResponse)
	err := c.cc.Invoke(ctx, PanettiereService_MakeDough_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *panettiereServiceClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PanettiereService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PanettiereServiceServer is the server API for PanettiereService service.
// All implementations must embed UnimplementedPanettiereServiceServer
// for forward compatibility.
type PanettiereServiceServer interface {
	MakeDough(context.Context, *DoughRequest) (*DoughResponse, error)
	Status(context.Context, *emptypb.Empty) (*StatusResponse, error)
	mustEmbedUnimplementedPanettiereServiceServer()
}

// UnimplementedPanettiereServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPanettiereServiceServer struct{}

func (UnimplementedPanettiereServiceServer) MakeDough(context.Context, *DoughRequest) (*DoughResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeDough not implemented")
}
func (UnimplementedPanettiereServiceServer) Status(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedPanettiereServiceServer) mustEmbedUnimplementedPanettiereServiceServer() {}
func (UnimplementedPanettiereServiceServer) testEmbeddedByValue()                           {}

// UnsafePanettiereServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PanettiereServiceServer will
// result in compilation errors.
type UnsafePanettiereServiceServer interface {
	mustEmbedUnimplementedPanettiereServiceServer()
}

func RegisterPanettiereServiceServer(s grpc.ServiceRegistrar, srv PanettiereServiceServer) {
	// If the following call pancis, it indicates UnimplementedPanettiereServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PanettiereService_ServiceDesc, srv)
}

func _PanettiereService_MakeDough_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoughRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanettiereServiceServer).MakeDough(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanettiereService_MakeDough_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanettiereServiceServer).MakeDough(ctx, req.(*DoughRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PanettiereService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PanettiereServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PanettiereService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PanettiereServiceServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PanettiereService_ServiceDesc is the grpc.ServiceDesc for PanettiereService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PanettiereService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "panettiere.v1.PanettiereService",
	HandlerType: (*PanettiereServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MakeDough",
			Handler:    _PanettiereService_MakeDough_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _PanettiereService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "panettiere/v1/service.proto",
}
